/** @type {import('tailwindcss').Config} */
import { nextui } from "@nextui-org/react";

module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        xxl: "1728px",
        xl: "1440px",
        lg: "1024px",
        md: "768px",
        sm: "640px",
        xs: "320px",
      },
      boxShadow: {
        "papa-sm": "0px 10px 16px 0px rgba(0, 0, 0, 0.04)",
        "papa-input": "-5px 5px 20px 0px rgba(0, 0, 0, 0.05)",
      },
      width: {
        smallBox: "var(--w-smallBox)",
        middleBox: "var(--w-middleBox)",
        largeBox: "var(--w-largeBox)",
        sidebar: "var(--w-sidebar)",
        content: "var(--w-content)",
        excludeSidebar: "var(--w-excludeSidebar)",
      },
      height: {
        header: "var(--h-header)",
        footer: "var(--h-footer)",
        ssBox: "var(--h-ssBox)",
        smallBox: "var(--h-smallBox)",
        middleBox: "var(--h-middleBox)",
        largeBox: "var(--h-largeBox)",
      },
      minWidth: {
        smallBox: "var(--w-smallBox)",
        middleBox: "var(--w-middleBox)",
        largeBox: "var(--w-largeBox)",
        sidebar: "var(--w-sidebar)",
        content: "var(--w-content)",
        excludeSidebar: "var(--w-excludeSidebar)",
      },
      minHeight: {
        header: "var(--h-header)",
        footer: "var(--h-footer)",
        smallBox: "var(--h-smallBox)",
        middleBox: "var(--h-middleBox)",
        largeBox: "var(--h-largeBox)",
      },
      maxWidth: {
        smallBox: "var(--w-smallBox)",
        middleBox: "var(--w-middleBox)",
        largeBox: "var(--w-largeBox)",
        sidebar: "var(--w-sidebar)",
        content: "var(--w-content)",
        excludeSidebar: "var(--w-excludeSidebar)",
      },
      maxHeight: {
        header: "var(--h-header)",
        footer: "var(--h-footer)",
        smallBox: "var(--h-smallBox)",
        middleBox: "var(--h-middleBox)",
        largeBox: "var(--h-largeBox)",
      },
      borderRadius: {
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
      },
      padding: {
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
      },
      gap: {
        sm: "0.25rem",
        md: "0.5rem",
        lg: "1.5rem",
        xl: "2rem",
        xxl: "2.5rem",
      },
      colors: {
        primary: {
          50: "var(--primary-50)",
          100: "var(--primary-100)",
          200: "var(--primary-200)",
          300: "var(--primary-300)",
          400: "var(--primary-400)",
          500: "var(--primary-500)",
          600: "var(--primary-600)",
          700: "var(--primary-700)",
          800: "var(--primary-800)",
          900: "var(--primary-900)",
        },
        secondary: {
          50: "var(--secondary-50)",
          100: "var(--secondary-100)",
          200: "var(--secondary-200)",
          300: "var(--secondary-300)",
          400: "var(--secondary-400)",
          500: "var(--secondary-500)",
          600: "var(--secondary-600)",
          700: "var(--secondary-700)",
          800: "var(--secondary-800)",
          900: "var(--secondary-900)",
        },
        grayWarm: {
          50: "var(--gray-warm-50)",
          100: "var(--gray-warm-100)",
          200: "var(--gray-warm-200)",
          300: "var(--gray-warm-300)",
          400: "var(--gray-warm-400)",
          500: "var(--gray-warm-500)",
          600: "var(--gray-warm-600)",
          700: "var(--gray-warm-700)",
          800: "var(--gray-warm-800)",
          900: "var(--gray-warm-900)",
        },
        grayCool: {
          50: "var(--gray-cool-50)",
          100: "var(--gray-cool-100)",
          200: "var(--gray-cool-200)",
          300: "var(--gray-cool-300)",
          400: "var(--gray-cool-400)",
          500: "var(--gray-cool-500)",
          600: "var(--gray-cool-600)",
          700: "var(--gray-cool-700)",
          800: "var(--gray-cool-800)",
          900: "var(--gray-cool-900)",
        },
        status: {
          success: "var(--status-success)",
          danger: "var(--status-danger)",
          warning: "var(--status-warning)",
        },
        layout: {
          background: "var(--layout-background)",
          divider: "var(--layout-divider)",
        },
        txt: {
          primary: "var(--txt-primary)",
          white: "var(--txt-white)",
          black: "var(--txt-black)",
        },
      },
      gridTemplateColumns: {
        list: "665fr 222fr 115fr 115fr 115fr",
      },
      zIndex: {
        dropdown: 100,
        backdrop: 150,
        modal: 200,
        toast: 250,
      },
    },
  },
  plugins: [nextui()],
};
